/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  bytes,
  mapSerializer,
  publicKey as publicKeySerializer,
  string,
  struct,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  expectPublicKey,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type RegisterC3InstructionAccounts = {
  user: Signer;
  state: PublicKey | Pda;
  userAccount?: PublicKey | Pda;
  systemProgram?: PublicKey | Pda;
};

// Data.
export type RegisterC3InstructionData = {
  discriminator: Uint8Array;
  github: string;
};

export type RegisterC3InstructionDataArgs = { github: string };

export function getRegisterC3InstructionDataSerializer(): Serializer<
  RegisterC3InstructionDataArgs,
  RegisterC3InstructionData
> {
  return mapSerializer<
    RegisterC3InstructionDataArgs,
    any,
    RegisterC3InstructionData
  >(
    struct<RegisterC3InstructionData>(
      [
        ['discriminator', bytes({ size: 8 })],
        ['github', string()],
      ],
      { description: 'RegisterC3InstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: new Uint8Array([154, 108, 206, 10, 70, 54, 38, 140]),
    })
  ) as Serializer<RegisterC3InstructionDataArgs, RegisterC3InstructionData>;
}

// Args.
export type RegisterC3InstructionArgs = RegisterC3InstructionDataArgs;

// Instruction.
export function registerC3(
  context: Pick<Context, 'eddsa' | 'programs'>,
  input: RegisterC3InstructionAccounts & RegisterC3InstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'sdpHelloWorld',
    '2G1CwDWtk1oYQGSVCU2WB7cMD5j3UgVwtm6737E4UGNV'
  );

  // Accounts.
  const resolvedAccounts = {
    user: { index: 0, isWritable: true as boolean, value: input.user ?? null },
    state: {
      index: 1,
      isWritable: true as boolean,
      value: input.state ?? null,
    },
    userAccount: {
      index: 2,
      isWritable: true as boolean,
      value: input.userAccount ?? null,
    },
    systemProgram: {
      index: 3,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: RegisterC3InstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.userAccount.value) {
    resolvedAccounts.userAccount.value = context.eddsa.findPda(programId, [
      bytes().serialize(new Uint8Array([115, 116, 117, 100, 101, 110, 116])),
      publicKeySerializer().serialize(
        expectPublicKey(resolvedAccounts.user.value)
      ),
      bytes().serialize(new Uint8Array([99, 51])),
    ]);
  }
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'systemProgram',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getRegisterC3InstructionDataSerializer().serialize(
    resolvedArgs as RegisterC3InstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
