/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  ClusterFilter,
  Context,
  Program,
  PublicKey,
} from '@metaplex-foundation/umi';
import {
  getSdpHelloWorldErrorFromCode,
  getSdpHelloWorldErrorFromName,
} from '../errors';

export const SDP_HELLO_WORLD_PROGRAM_ID =
  '2G1CwDWtk1oYQGSVCU2WB7cMD5j3UgVwtm6737E4UGNV' as PublicKey<'2G1CwDWtk1oYQGSVCU2WB7cMD5j3UgVwtm6737E4UGNV'>;

export function createSdpHelloWorldProgram(): Program {
  return {
    name: 'sdpHelloWorld',
    publicKey: SDP_HELLO_WORLD_PROGRAM_ID,
    getErrorFromCode(code: number, cause?: Error) {
      return getSdpHelloWorldErrorFromCode(code, this, cause);
    },
    getErrorFromName(name: string, cause?: Error) {
      return getSdpHelloWorldErrorFromName(name, this, cause);
    },
    isOnCluster() {
      return true;
    },
  };
}

export function getSdpHelloWorldProgram<T extends Program = Program>(
  context: Pick<Context, 'programs'>,
  clusterFilter?: ClusterFilter
): T {
  return context.programs.get<T>('sdpHelloWorld', clusterFilter);
}

export function getSdpHelloWorldProgramId(
  context: Pick<Context, 'programs'>,
  clusterFilter?: ClusterFilter
): PublicKey {
  return context.programs.getPublicKey(
    'sdpHelloWorld',
    SDP_HELLO_WORLD_PROGRAM_ID,
    clusterFilter
  );
}
